### ISSUE TITLE
Cannot call any api call,keep getting ambiguous argument error in compile time

### ISSUE THREAD

**Issue by eminarcissus** [s4cha/ws#38]
let w = WS("http://localhost:4000/api")
        let result = w.get("test",params: [:])

getting me 
Ambiguous use of 'get(_:params:)'

        let w = WS("http://localhost:4000/api")
        let result = w.get("test")

with a error of 
/Users/misuzi/developing/ios/dream_garden_manage/dream_garden_manage/Login.swift:124:22: Ambiguous use of 'get(_:params:)'

        let w = WS("http://localhost:4000/api")
        let result = w.post("test",params: ["name": "123"])

/Users/misuzi/developing/ios/dream_garden_manage/dream_garden_manage/Login.swift:124:22: Ambiguous use of 'post(_:params:)'

I'm using pod to install ws 2.0.0 and swift 3.0

Any suggestions?

**Comment by maxkonovalov** [comment]
Hello @eminarcissus 
This happens because there are multiple implementations of `get` function. To make it work, you need to be explicit about the type of result expect.
Try specifying the type like this:
```swift
let result: Promise<JSON> = w.get("test")
```
or wrap the entire API call into a separate method:
```swift
func test() -> Promise<JSON> {
    return w.get("test")
}
```
If you use **Arrow** for your models parsing, you can change the `JSON` type to your custom model type.

**Comment by eminarcissus** [comment]
Ahhh，thx for the help, the problem roots from I did refered another JSON lib which makes JSON callback ambiguous, I will close the issue now, thx for the help 👍
