### ISSUE TITLE
How to install without Carthage

### ISSUE THREAD

**Issue by NexusMTO** [s4cha/ws#5]
I'm noob.

**Comment by s4cha** [comment]
@zephiro That is a good question :p 
I have to admit I have never tried at the moment.

Carthage is pretty useful since it takes care of pulling dependencies such as Arrow, then and Alamofire.
What's cool is that it really is transparent. What I mean is that you could just use carthage on the side to pull and build dependencies and manually link frameworks to your Xcode project.

Without Carthage, I'd see 2 solutions : 
1 - Copy paste all the source code : ws / then / Arrow / Alamofire which doesn't sound like a lot of fun ;)
2 - Manually link the frameworks  (ws + dependencies) by A grabbing `.framework`s them on each repo, or B use Carthage to build them

Hope it helps :)

PS : I am curious and would love to know what would be your preferred way and the reason as to why you'd rather not use Carthage. We really want to make this as easy to integrate as possible :)

**Comment by florentdouine** [comment]
Hi @s4cha. Why did you choose not to use Cocoapods for this project ?

**Comment by Unstop-M** [comment]
Thanks a lot. I install perfect.

**Comment by s4cha** [comment]
@zephiro, glad to know it worked out for you :)

@florentdouine I personally avoid Cocoapods for certain reasons, one being that it forces you to have a workspace. 
A very good talk that made me favour Carthage is: https://realm.io/news/swift-dependency-management-with-carthage/ 

Simplicity should always win :)

However, I understand Cocoapods is widely used and Pod Support should be on our roadmap for practical reasons :)

**Comment by s4cha** [comment]
Just referenced this in README, closing it for now.
